from fpdf import FPDF
from datetime import datetime
from staticmap import StaticMap, Polygon
import os

def create_pdf(analysis_data, filename="flight_report.pdf"):
    """
    Membuat laporan PDF formal lengkap dengan visualisasi peta statis.
    analysis_data: dictionary berisi area, efficiency, dan polygon coords.
    """
    temp_map_path = "temp_map.png"
    try:
        m = StaticMap(800, 400, url_template='https://tile.openstreetmap.org/{z}/{x}/{y}.png')
        
        poly_coords = analysis_data.get('polygon', [])
        
        if poly_coords:
            map_poly_coords = [(lon, lat) for lat, lon in poly_coords]
            
            polygon = Polygon(map_poly_coords, '#FFD70077', '#FFD700', 3)
            m.add_polygon(polygon)
            
            image = m.render()
            image.save(temp_map_path)

        pdf = FPDF()
        pdf.add_page()
        
        pdf.set_font("Arial", 'B', 16)
        pdf.cell(0, 10, "FLIGHT MONITORING REPORT - AMX UAV", ln=True, align='C')
        pdf.set_font("Arial", size=10)
        pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align='C')
        pdf.ln(5)
        
        pdf.line(10, 32, 200, 32)
        pdf.ln(10)
        
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Flight Analysis Summary:", ln=True)
        pdf.set_font("Arial", size=11)
        
        pdf.cell(70, 10, "Metric", border=1, fill=False)
        pdf.cell(70, 10, "Value", border=1, ln=True)
        
        pdf.cell(70, 10, "Total Area Coverage", border=1)
        pdf.cell(70, 10, f"{analysis_data['total_area_coverage']}", border=1, ln=True)
        
        pdf.cell(70, 10, "Monitoring Efficiency", border=1)
        pdf.cell(70, 10, f"{analysis_data['monitoring_efficiency']}", border=1, ln=True)
        
        pdf.ln(10)

        if os.path.exists(temp_map_path):
            pdf.set_font("Arial", 'B', 12)
            pdf.cell(0, 10, "Area Visualization:", ln=True)
            pdf.image(temp_map_path, x=10, y=pdf.get_y(), w=190)
            pdf.ln(100)

        pdf.set_y(-30)
        pdf.set_font("Arial", 'I', 8)
        pdf.multi_cell(0, 5, "Note: This report is automatically generated by the AMX Flight Monitoring System.\nVisual representation is based on the calculated convex hull of the flight log coordinates.")
        
        pdf.output(filename)
        
        if os.path.exists(temp_map_path):
            os.remove(temp_map_path)
            
        return True
    except Exception as e:
        print(f"Error creating PDF: {e}")
        if os.path.exists(temp_map_path):
            os.remove(temp_map_path)
        return False